### ISSUE TITLE
Priority override don't work

### ISSUE THREAD

**Issue by ucolaf** [kee-org/keepassrpc#105]
After update, Priority override has no function ?

**Comment by knubew** [comment]
I have the same issue with the "Priority override" since version 1.12.1.

I have 19 different logins for an URL and set them from 1 to 19 in the priority override and each with an "exact URL match". The order of these different logins that are displayed in the browsers select list, have absolutely nothing to do with the order that I defined in the priority override.

**Comment by mberger-git** [comment]
Hi, on 1.13 priority override does not work as well.

**Comment by luckyrat** [comment]
See https://forum.kee.pm/t/prioritising-and-sorting-matched-entries-in-kee-3-5-and-higher/3112 and now also #138 and #137
