### ISSUE TITLE
Keepass unable to resolve the references in password fields

### ISSUE THREAD

**Issue by momcilo78** [kee-org/keepassrpc#108]
I am not sure if this belongs to the plugin part of keepass or the firefox plugin, but I recently I have noticed that kee plugin fills in what ever is in the password field, and simply ignores the referenced field in another entry. 
E.g. if I have an entry that contains the master password, and a number of entries for services that use that same account, it used to be possible to use the references in password field, so once the password change occurs, I do not need to change 200+ entries. 

Somewhere in the last 3 weeks this behavior has changed and kee/keepassrpc do not resolve the references anymore. 2

I assume this is in the keepassrpc level, but I may be wrong. 
Keepass 2: 2.45
KeePassRPC: 1.12.1.0
Kee: 3.5.19
Firefox: 7912

**Comment by dlech** [comment]
This feature has to be manually enabled since v1.8 or so. See https://forum.kee.pm/t/placeholder-handling/1100/1

**Comment by momcilo78** [comment]
Thanks, I can confirm it works.
It looks like I will have to do this on the database level despite risk. 
In short I have a limited number o entries that contain actual password values. One of this entry is the account for the LDAP hosted account, and all services that I normally access are connected to the LDAP. This means that each service has its own entry, which references the password from the master entry. 

With present model: 
- I grant access on database level (e.g. also potentially disclosing other actual passwords)
- I can go the service entry and explicitly enable the feature, but this means to many services to edit

Would it be possible to mark one or more actual entries as "safe" to be referenced by other entries?

**Comment by luckyrat** [comment]
KeePass does the dereferencing of placeholders rather than KeePassRPC so the concept of a "safe to be referenced" entry would be best implemented there rather than in this plugin. I don't imagine it would be a simple feature to add and may still require some changes to API usage in this (and other) plugins so maybe don't get your hopes up for it being implemented but I suppose it doesn't hurt to check out the KeePass discussion forums for similar proposals and suggest it if it's not already there - https://sourceforge.net/p/keepass/discussion/

By the way, in future, using the [community forum](https://forum.kee.pm/) will likely result in faster help (I've just added a GitHub issue template to make that clearer for people arriving at this repo from routes that don't already mention that).
