### ISSUE TITLE
After saving the database, Kee will not work properly

### ISSUE THREAD

**Issue by ghost** [kee-org/keepassrpc#114]
If I save a database after that the auto login does not work anymore. 
When I open the database with the Kee Add-on, a second tab is opened in KeePass with the locked database.
If I open the database in the tab again, Kee will work again without problems. Until I save the database again.

KeePass 2.45
KeePassRPC 1.13
Kee 3.5

**Comment by luckyrat** [comment]
I don't think this issue is specific/unique to KeePassRPC. If you're still interested in improvements related to this issue, please use the [Kee community forum](https://forum.kee.pm/) and provide more information so others can help progress this. In future, using the community forum will likely result in faster help (I've just added a GitHub issue template to make that clearer for people arriving at this repo from routes that don't already mention that).
