### ISSUE TITLE
Generate new password does not work

### ISSUE THREAD

**Issue by viktor-nikolaev** [kee-org/keepassrpc#116]
After updating to one of the recent version generating new password from Chrome's right-click menu stopped to work.

**Steps to reproduce:**

1. In Chrome right-click somewhere on a page
2. Open Kee - password manager -> Generate new password
3. Choose the type of password

**Expected result**
Password is generated and is copied to the clipboard.

**Actual result**
Nothing gets generated and nothing gets copied to the clipboard

**Comment by Deshroom** [comment]
Hi,

it's working with Firefox but not with Chrome. Do you found fix for Chrome, I need it ASAP. Thanks.

**Comment by luckyrat** [comment]
I don't think this issue is specific/unique to KeePassRPC. If you're still interested in improvements related to this issue, please use the [Kee community forum](https://forum.kee.pm/) and provide more information so others can help progress this. In future, using the community forum will likely result in faster help (I've just added a GitHub issue template to make that clearer for people arriving at this repo from routes that don't already mention that).
