### ISSUE TITLE
Hide expired credentials

### ISSUE THREAD

**Issue by gabriele-v** [kee-org/keepassrpc#119]
Hi,
would it be possible to don't suggest expired credentials? Maybe a master setting could be added for this.

I know I could check "hide this entry from kee" but it would be helpful to have it automatically done when an entry expires.

Thanks

**Comment by nitz** [comment]
I was looking for this feature too. It seems Kee ignores entries in the recycle bin (which is good! But, that behavior doesn't seem adjustable either.) I'd rather still be able to keep some expired passwords where they are and not need to set the 'hide this entry from kee' manually on each one.

**Comment by luckyrat** [comment]
I don't think this issue is specific/unique to KeePassRPC. If you're still interested in improvements related to this issue, please use the [Kee community forum](https://forum.kee.pm/) and provide more information so others can help progress this. Probably there is already some requests and discussions relating to expiring entries.
