### ISSUE TITLE
Access with python?

### ISSUE THREAD

**Issue by navxio** [kee-org/keepassrpc#12]
Hi,

Is the keepass rpc api exposed such that it can be accessed by other apps/scripts?

**Comment by dlech** [comment]
Yes, it uses https via a TCP socket so just about anything (including python) can talk to it. There is some information on the KeeFox wiki: https://github.com/kee-org/KeeFox/wiki/en-%7C-Technical-%7C-KeePassRPC-detail

You can also look at the KeeFox extension as a reference implementation: https://github.com/kee-org/KeeFox/blob/master/Firefox%20addon/KeeFox/modules/kprpcClient.js

**Comment by ThomFri** [comment]
Hi [navxio](https://github.com/navxio),
I know some time has passed since your original post, but I'd be interested to know if you've programmed (or found) a Python library to interact with keepassrpc? I currently use keepasshttp (the name is identical for the KeePass plugin and the Python library), but I'd like to switch since keepasshttp hasn't been updated in years. However, I would like to keep my current processes unchanged, i.e. Python should read from my unlocked database and not the file directly etc. so I don't have to store my database key anywhere near my programming projects.
Many thanks in advance!

**Comment by navxio** [comment]
@ThomFri sorry I haven't.. I've moved on to other pw managers.
