### ISSUE TITLE
Asked for every entry to save

### ISSUE THREAD

**Issue by CennoxX** [kee-org/keepassrpc#148]
With the change to version 2, I am now asked once for every entry I open and close with escape key if I want to save my changes. Even if I have all Kee-specific settings set to the default values. If I save, the entry now has the plugin data KPRPC JSON. Is there anything I can do, to stop being asked to save the entry every time I open and close an entry? Can I save them all at once, etc?

**Comment by luckyrat** [comment]
Please can you post this on the community forum? Maybe someone else can reproduce it (I can't) and help us understand if there is something that we need to change or some way you can work around what is going on. https://forum.kee.pm

**Comment by adoerler** [comment]
Hi,

we see the same behaviour using Keepass 2.60 and Keepass-RPC 2.0.2.0.
The "funny thing" is, that using the cancel button works, while pressing X or ESC triggers the change.
Saving the change once "fixes" the problem, but this does not seem practicable with thousends of entries in the DB.

**Comment by schmurtzm** [comment]
It seems that many users are experiencing this problem, and this issue should remain open for further discussion. Most users don’t realize that this behavior is a bug, and many others are unaware of GitHub issues or even the Kee forum.

A discussion has already started here:
https://forum.kee.pm/t/keepassrpc-asks-to-save-when-no-known-changes-were-made/4580

On this thread alone (which requires creating an account just to say "me too" 😩), 9 people have already shared their frustration.

There’s also a pull request addressing the issue here:
https://github.com/kee-org/keepassrpc/pull/153

It would be great to merge it or at least build a test version for people concerned by this bug.
