### ISSUE TITLE
Bug reports: KeePassRPC

### ISSUE THREAD

**Issue by michaeldcwolf** [kee-org/keepassrpc#149]
Keepass Version 2.57 64bit
KeePassRPC 2.0.2

1. open Keepass item double-click
2. close it with X (right corner)
3. Something will be changed in item, hence it ask for confirmation

This happens only with KeePassRPC is installed. In the history you see that there is an entry for "KPRPC JSON (+)"
This is not nice :-)

**Comment by tofublock** [comment]
Just updated to 2.0.2 (I must have been on 1.6 before, but can't be sure) and I get the "Save Changes?" dialog now as well for every entry I touch. This behaviour is a bit concerning, since it creates the "what did I touch?!" moment.

Apologies if the information is available and I didn't find it, but can we get an explanation why this is happening specifically, and is there a way to add the JSON field to all entries in the database in a controlled fashion once and not have it happen again?

Thanks for the good work you're doing!

**Comment by luckyrat** [comment]
There's not enough to go on here to specify a bug or fix so closing in favour of discussion at https://forum.kee.pm/t/keepassrpc-asks-to-save-when-no-known-changes-were-made/4580/3
