### ISSUE TITLE
Option to remove KPRPC JSON entries

### ISSUE THREAD

**Issue by Magneticdud** [kee-org/keepassrpc#16]
Because of this [breaking bug](https://github.com/kee-org/browser-addon/issues/55) i had to stop using Kee on all my systems

Now all my entries have the KPRPC json in them, imho it would be neat to have a button to "uninstall" the plugin (meaning: remove the JSON entry from all the password entries)

**Comment by luckyrat** [comment]
We won't implement this but at some point in the future, the recent improvements to KeePass will allow us to store the data somewhere that is less visible (although still possible to delete in case you're worried about the few KBs of extra data rather than the visible entry in the list of custom strings).

See #24
