### ISSUE TITLE
What is 'publicSuffixDomainCache.txt'?

### ISSUE THREAD

**Issue by electrofloat** [kee-org/keepassrpc#22]
There's 'publicSuffixDomainCache.txt' in my KeePass config folder.
Short googling shows that it is related to keepassrpc.

What is this used for?

**Comment by luckyrat** [comment]
It's the cache of the [public suffix list of domains](https://publicsuffix.org/). It enables us to identify what constitutes a domain vs a subdomain in order to increase entry matching accuracy.

It's updated periodically but broadly just gets downloaded from the internet and stored locally on your machine. Deleting it shouldn't cause a serious problem but it will be recreated almost straight away and sometimes cause a noticeable performance problem in Kee when this happens so there's really no good reason to touch it.
