### ISSUE TITLE
Port in use issues - Change default port?

### ISSUE THREAD

**Issue by msgerbs** [kee-org/keepassrpc#56]
Lately I've had several instances of a random background service deciding to use port 12546, causing KeePassRPC to be unable to listen on that port. Shouldn't KeePassRPC use a port in the lower static range so as to avoid this issue, or somehow use a dynamic port itself (or a named pipe instead)? For the record, I know I can change the port, but I would argue that the problem is with KeePassRPC's default config, not on my end. Static port bindings shouldn't be used in the dynamic port range, especially in the lower 12000-25000 range which is almost always quite heavily populated on a default Windows box. If changing the port to a lower port number or using a dynamic port isn't a viable solution, could having KeePassRPC run as a service at system startup resolve the issue instead?

**Comment by luckyrat** [comment]
12546 doesn't fall into the dynamic port range, although it is possible to manually configure Windows to use a different range and perhaps this is what has happened on your machine at some point in the past (or maybe via an active directory domain group policy)

Named pipes do (or at least did) not have wide cross-platform support or a feasible way to utilise them from within web browsers and there needs to be some known port for Kee to attempt to connect to so using a dynamic port isn't an option either. KeePassRPC has to run within the confines of a KeePass plugin which, at least currently, can not run as a service - I've seen no indication that this would ever be supported by KeePass either.

Changing the default port or the connection method will be very disruptive to existing users (especially the non-technical ones) so I'm not likely to consider it unless some future change to port standards results in widespread problems with the current port.

If there are specific Windows services that have been configured to use random ports on your machine, it's probably best to reconfigure them so that they can behave more predictably since such behaviour is going to clash with many other services and applications as well as KeePassRPC.

**Comment by Dedrus** [comment]
In case you want to check which program uses port you can type this in powershell
` Get-Process -Id (Get-NetTCPConnection -LocalPort 12546).OwningProcess`
