### ISSUE TITLE
KeePassRPC 1.8.0 not compatible with KeePass 2.41 - win7x64

### ISSUE THREAD

**Issue by peterpepo** [kee-org/keepassrpc#65]
Hello,
Keepassrpc 1.8.0 seems to be not compatible with Keepass 2.41 on my Windows7x64 setup.
I had this issue couple times in the past, and it always resolved "by itself" - I simply forgot and the remembered about integration, so I moved the file downloaded (KeePassRPC.plgx) months ago to plugins folder and it started working magically.

I've reinstalled windows on my ancient laptop yesterday and have the very same problem again.

On the other hand, same keepass + keepass rpc version work fine on my windows10 machine.

I'm attaching screenshots for more information.
![keepass_version](https://user-images.githubusercontent.com/2683131/51087465-15af1c00-1754-11e9-87a1-647ec88087a3.PNG)
![keepassrpc_error](https://user-images.githubusercontent.com/2683131/51087466-1942a300-1754-11e9-8e40-a0c31fe292af.PNG)

Any idea, what could be the issue?

**Comment by dlech** [comment]
Errors with System.Drawing usually mean that KeePass.exe is running with the wrong .NET runtime. It could be that if this is a fresh install of Win7, then you only have .NET 3.5 and KeePassRPC requires at least 4.0. This problem has probably resolved itself in the past because you installed something else that included .NET 4.0 or higher.

**Comment by peterpepo** [comment]
Thanks @dlech, installing latest .NET - v4.7.2 solved the issue.
