### ISSUE TITLE
Client request for authorization with Kee should have the browser name

### ISSUE THREAD

**Issue by gforge** [kee-org/keepassrpc#76]
I recently started getting a ton of dialogs with the request:

> "Kee" claims that it is "A browser addon that securely enables automatic login to most websites. Previously known as KeeFox.".

Originally I thought that this could be related to https://github.com/kee-org/KeeFox/issues/252 but after some debugging I realized that Chrome was starting up in the background causing these requests. My suggestions are:

- The request should contain which browser it originates from
- The request should not be triggered when Chrome is running in the background

**Comment by luckyrat** [comment]
It's a "maybe" for both suggestions but it needs more planning to work out if either are technically possible and whether we want to implement them.

If you want to discuss on the [community forum](https://forum.kee.pm) we could see if anyone has ideas for how it could be implemented and/or wants to volunteer to do the work.

I'll close this now though because it's too broad to be a specific implementation issue.
