### ISSUE TITLE
Fail to load when port is in use

### ISSUE THREAD

**Issue by Mincka** [kee-org/keepassrpc#79]
Hello,

Would it be possible to gracefully handle the exception (still load the extension) when the port is in use, so it would be possible to change it using the interface?

For some reason, I had to change the default port while the default one was in use by some software I could not identify and stop. Since the plugin won't load when the port set is in use, the only way to update it and load the extension was to find and update the config section.
```
<Item>
  <Key>KeePassRPC.webSocket.port</Key>
  <Value>12499</Value>
</Item>
```

Thanks!

**Comment by luckyrat** [comment]
You can also supply a command line parameter in case this issue re-occurs for you: https://forum.kee.pm/t/keepassrpc-port/2360

Establishing the port is currently fundamental to the startup of the plugin and it can't be re-initialised on demand. It's a decade since I wrote that code so I can't say with certainty whether it needs to keep behaving in that way but I am wary of changing something in the security critical startup path without spending more time than I currently have available to specify and verify the alteration.
