### ISSUE TITLE
PSL download fails, if %APPDATA%\Keepass does not exist

### ISSUE THREAD

**Issue by casperklein** [kee-org/keepassrpc#95]
System: Windows 10
Keepass: 2.44 Portable

I had an issue, where Kee Domain Matching did not work.

After reading [this](https://forum.kee.pm/t/problems-when-keepass-cant-determine-a-domain-name-using-the-psl/2346), I recognized, that there is no `publicSuffixDomainCache.txt` on my system.

I played a bit around and concluded the following things:

- `publicSuffixDomainCache.txt` is not downloaded, if %APPDATA%\Keepass does not exist.
- other Keepass functions that work with files from `%APPDATA%\Keepass`, automatically create that directory if needed, e.g. when creating a database that is bound to the windows account.
- setting a custom Path in `KeePass.config.xml` does not seem to work. I tried the following:
```
    <Custom>
		<Item>
			<Key>KeePassRPC.publicSuffixDomainCache.path</Key>
			<Value>C:\PortableApps\Keepass</Value>
		</Item>
    </Custom>
```

My questions are:

1. Why is the `%APPDATA%\Keepass directory not created on demand?
1. What is the proper way to debug KeepassRPC? There seems to be no log file or anything. Knowing that downloading the PSL fails due a not existing directory would have saved me a lot of time.
1. What's wrong with my approach, setting a custom path for PSL? I wasn't able to debug this further, see point above.

Thank you!

**Comment by luckyrat** [comment]
1) That directory is used for the entirety of the KeePass application so if it does not exist, it is not for us as a mere plugin to interfere with that situation. For example, it would be bad to automatically create this folder in an environment where KeePass is running as a portable (not installed) executable.

When saving to this location fails (such as if the directory does not exist or permission is denied) KeePassRPC tries instead to write to the executable folder (in most cases that's in `Program Files (x86)` and in most cases this will fail due to insufficient permissions.

2) See https://forum.kee.pm/t/troubleshooting/560/1#heading--debug-the-problem

3) I would expect setting a custom path would work in the way you tried. If you're still struggling with this (sorry for the delay!) perhaps try including a trailing slash. Although, if that directory is where your KeePass executable resides, you should (see above) find that the problem comes down to that executable directory being read-only or otherwise unavailable for KeePassRPC to write to.
