### ISSUE TITLE
KeePassRPC causes Master Key dialog to open immediately after inactivity lock

### ISSUE THREAD

**Issue by dixonte** [kee-org/keepassrpc#96]
**Summary**

I have my KeePass configured with the option 'Lock workspace after global user inactivity (seconds)' enabled. For a while now, I've been plagued by an issue where KeePass will pop up immediately after auto locking requesting that I unlock it with the master key. I've recently discovered this is because of KeePassRPC. This is quite annoying when I am watching YouTube, for example.

Another plugin I use, KeeAgent, has an option 'Unlock all databases when a client sends a request'. It would be useful if KeePassRPC had a similar option, or could otherwise cleverly decide if it actually needs to open the database or not.

**Reproduction**

1. Enable 'Lock workspace after global user inactivity' and set the timeout to something low e.g. 10 seconds
2. Make sure that KeePassRPC is installed and configured normally.
3. Minimise KeePass to the tray and leave the PC idle for the configured period. The main KeePass window should pop up, with the master key dialog over the top.
4. Exit KeePass.
5. Go to the KeePass plugins directory and rename KeePassRPC.plgx to KeePassRPC.plgx.bak.
6. Start KeePass and repeat the test. KeePass should this time lock itself silently when the timeout expires.

**Comment by luckyrat** [comment]
I guess this relates to the PR I just found and closed. It's been a long time since you reported this and I'm not sure I fully understand the described behaviour so if this is still a problem with the latest versions of all relevant software please can you check on the community forum for similar discussions and post there so we can get input from other users? In future, using the [community forum](https://forum.kee.pm/) will likely result in faster help (I've just added a GitHub issue template to make that clearer for people arriving at this repo from routes that don't already mention that).
